### ISSUE TITLE
Exception in provided 3d example: Inconsistent number of specified drift terms supplied

### ISSUE THREAD

**Issue by 1kastner** [bsmurphy/PyKrige#71]
I took your example provided at https://github.com/bsmurphy/PyKrige#three-dimensional-kriging-example and tried to run it:

    >>> k3d, ss3d = uk3d.execute('grid', gridx, gridy, gridz, specified_drift_arrays=[xg, yg, zg])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "C:\Users\current-user\AppData\Roaming\Python\Python36\site-packages\pykrige\uk3d.py", line 775, in execute
        raise ValueError("Inconsistent number of specified drift terms supplied.")
    ValueError: Inconsistent number of specified drift terms supplied.

That does not look like what I expected...

**Comment by rth** [comment]
@1kastner Thanks for reporting this. I can confirm that the 3D example in the readme fails to run with the above error on `1.3.0` and `1.4.dev0` (master branch).  cc @bsmurphy

**Comment by bsmurphy** [comment]
In setting up the `uk3d` object, I think the call should include the `specified_drift` kwarg like so:
```python
specified_drift=[data[:, 0], data[:, 1], data[:, 2]]
```
not
```python
specified_drift=[data[:, 0], data[:, 1]]
```
as it currently is...

So the complete code section should look like this:
```python
zg, yg, xg = np.meshgrid(gridz, gridy, gridx, indexing='ij')
uk3d = UniversalKriging3D(data[:, 0], data[:, 1], data[:, 2], data[:, 3],
                                                  variogram_model='linear', drift_terms=['specified'],
                                                  specified_drift=[data[:, 0], data[:, 1], data[:, 2]])
k3d, ss3d = uk3d.execute('grid', gridx, gridy, gridz, specified_drift_arrays=[xg, yg, zg])
```
Let me know if that fixes the problem. I'll update the README to be correct...
